[package]
name = "quay-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "quay"
path = "src/main.rs"

[dependencies]
quay-core.workspace = true
quay-forge.workspace = true
quay-store.workspace = true
quay-sync.workspace = true
time.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
