[package]
name = "quay-store"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
quay-core.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true

[dev-dependencies]
criterion.workspace = true
quay-core.workspace = true
tempfile.workspace = true

[lib]
bench = false

[[bench]]
name = "inbox"
harness = false
